// @generated by lumen-icon-gen (ADR-0008 PoC). Do not edit by hand.
// Icons derived from Lucide (ISC License). Coordinates are normalized 0..1.

fn paint_arrow_down(painter: &egui::Painter, rect: egui::Rect, stroke: egui::Stroke) {
    painter.add(egui::Shape::line(vec![
        at(rect, 0.5000, 0.2083),
        at(rect, 0.5000, 0.7917),
    ], stroke));
    painter.add(egui::Shape::line(vec![
        at(rect, 0.7917, 0.5000),
        at(rect, 0.5000, 0.7917),
        at(rect, 0.2083, 0.5000),
    ], stroke));
}

fn paint_arrow_left(painter: &egui::Painter, rect: egui::Rect, stroke: egui::Stroke) {
    painter.add(egui::Shape::line(vec![
        at(rect, 0.7917, 0.5000),
        at(rect, 0.2083, 0.5000),
    ], stroke));
    painter.add(egui::Shape::line(vec![
        at(rect, 0.5000, 0.7917),
        at(rect, 0.2083, 0.5000),
        at(rect, 0.5000, 0.2083),
    ], stroke));
}

fn paint_arrow_right(painter: &egui::Painter, rect: egui::Rect, stroke: egui::Stroke) {
    painter.add(egui::Shape::line(vec![
        at(rect, 0.2083, 0.5000),
        at(rect, 0.7917, 0.5000),
    ], stroke));
    painter.add(egui::Shape::line(vec![
        at(rect, 0.5000, 0.2083),
        at(rect, 0.7917, 0.5000),
        at(rect, 0.5000, 0.7917),
    ], stroke));
}

fn paint_arrow_up(painter: &egui::Painter, rect: egui::Rect, stroke: egui::Stroke) {
    painter.add(egui::Shape::line(vec![
        at(rect, 0.2083, 0.5000),
        at(rect, 0.5000, 0.2083),
        at(rect, 0.7917, 0.5000),
    ], stroke));
    painter.add(egui::Shape::line(vec![
        at(rect, 0.5000, 0.7917),
        at(rect, 0.5000, 0.2083),
    ], stroke));
}

fn paint_chevron_left(painter: &egui::Painter, rect: egui::Rect, stroke: egui::Stroke) {
    painter.add(egui::Shape::line(vec![
        at(rect, 0.6250, 0.7500),
        at(rect, 0.3750, 0.5000),
        at(rect, 0.6250, 0.2500),
    ], stroke));
}

fn paint_chevron_up(painter: &egui::Painter, rect: egui::Rect, stroke: egui::Stroke) {
    painter.add(egui::Shape::line(vec![
        at(rect, 0.7500, 0.6250),
        at(rect, 0.5000, 0.3750),
        at(rect, 0.2500, 0.6250),
    ], stroke));
}

