//! `lumen-theme-gen` — scaffold lumen-ui themes from a RON palette.
//!
//! * `lumen-theme-gen template`          → print a starter palette (RON, from DarkTheme).
//! * `lumen-theme-gen gen <palette.ron>` → print Rust code for a `PaletteTheme`.
//!
//! Edit the RON palette by hand, then `gen` it into a theme you can paste into a crate.

use std::process::ExitCode;

use lumen_ui_core::{Colors, DarkTheme, Theme};

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().collect();
    match args.get(1).map(String::as_str) {
        Some("template") => {
            print_template();
            ExitCode::SUCCESS
        }
        Some("gen") => {
            let Some(path) = args.get(2) else {
                eprintln!("usage: lumen-theme-gen gen <palette.ron>");
                return ExitCode::from(2);
            };
            match std::fs::read_to_string(path) {
                Ok(source) => match ron::from_str::<Colors>(&source) {
                    Ok(colors) => {
                        print!("{}", codegen(&colors));
                        ExitCode::SUCCESS
                    }
                    Err(err) => {
                        eprintln!("parse error in {path}: {err}");
                        ExitCode::from(1)
                    }
                },
                Err(err) => {
                    eprintln!("cannot read {path}: {err}");
                    ExitCode::from(1)
                }
            }
        }
        _ => {
            eprintln!(
                "lumen-theme-gen — usage:\n  template            emit a starter palette (RON)\n  gen <palette.ron>   emit Rust PaletteTheme code"
            );
            ExitCode::from(2)
        }
    }
}

fn print_template() {
    let colors = DarkTheme::new().tokens().colors.clone();
    // SAFETY: serializing a fixed, fully-populated struct cannot fail.
    let ron = ron::ser::to_string_pretty(&colors, ron::ser::PrettyConfig::default())
        .expect("serializing Colors to RON is infallible");
    println!("{ron}");
}

fn codegen(colors: &Colors) -> String {
    let fields = [
        ("background", colors.background),
        ("surface", colors.surface),
        ("surface_variant", colors.surface_variant),
        ("primary", colors.primary),
        ("on_primary", colors.on_primary),
        ("secondary", colors.secondary),
        ("on_secondary", colors.on_secondary),
        ("success", colors.success),
        ("on_success", colors.on_success),
        ("warning", colors.warning),
        ("on_warning", colors.on_warning),
        ("danger", colors.danger),
        ("on_danger", colors.on_danger),
        ("text", colors.text),
        ("text_muted", colors.text_muted),
        ("border", colors.border),
    ];

    let mut body = String::new();
    for (name, color) in fields {
        body.push_str(&format!(
            "        {name}: Color32::from_rgba_unmultiplied({}, {}, {}, {}),\n",
            color.r(),
            color.g(),
            color.b(),
            color.a(),
        ));
    }

    format!(
        "// Generated by lumen-theme-gen — edit the palette, then regenerate.\n\
         use egui::Color32;\n\
         use lumen_ui_core::{{Colors, Elevation, Motion, PaletteTheme, Radius, Spacing, ThemeMode, Tokens, Typography}};\n\
         \n\
         #[must_use]\n\
         pub fn my_theme() -> PaletteTheme {{\n\
         \x20   let colors = Colors {{\n{body}    }};\n\
         \x20   PaletteTheme::new(\n\
         \x20       Tokens {{\n\
         \x20           colors,\n\
         \x20           spacing: Spacing::default(),\n\
         \x20           radius: Radius::default(),\n\
         \x20           typography: Typography::default(),\n\
         \x20           elevation: Elevation::default(),\n\
         \x20           motion: Motion::default(),\n\
         \x20       }},\n\
         \x20       ThemeMode::Dark,\n\
         \x20   )\n\
         }}\n"
    )
}
